#!/bin/bash

top="$(pwd)"  #top default path is "."

usage() { 
    echo "USAGE: $0 command args"
    echo "     command - one of the supported commands"
    echo "     args    - the command arguments"
    echo "Supported commands:"
    echo " - makemodules [-C <path>] [-j <n>] [-v] configuration"
    echo " - cleanmodules [-C <path>] configuration"
    echo " - configureioc [-C <path>] configuration"
    exit 1; 
}

# the first non-optional parameter must be the config file
if (( $# < 1 )); then
    usage
fi

command="$1"
shift 1
args=" $@"

if [ ! -r $command ]; then
    echo "ERROR: command $command not found"
    exit 1
fi


if ! . $command $args; then
    exit 1
fi

echo "--- Completed ---"