FROM ubuntu:latest

ENV PATH="${HOME:-/root}/.local/bin:${PATH}"

RUN apt-get update \ 
    && apt-get -y install \
        git \
        build-essential \
        libreadline-dev \
        re2c

COPY . /epicsmng

RUN sh /epicsmng/install.sh \
    && rm -rf /epicsmng \
    && echo "" >> ${HOME:-/root}/.config/epicsmng/settings/user.settings \
    && echo "base_url=\"https://github.com/epics-base/epics-base\"" >> ${HOME:-/root}/.config/epicsmng/settings/user.settings